<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.6</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <groupId>com.github.emw7.platform</groupId>
  <artifactId>emw7-platform</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>EMW7 Platform</name>
  <packaging>pom</packaging>

  <modules>
    <module>platform-core</module>
    <module>platform-error</module>
    <module>platform-i18n</module>
    <module>platform-log</module>
    <module>platform-auth-api</module>
    <module>platform-discovery-api</module>

    <module>platform-service-core</module>
    <module>platform-service-runtime</module>

    <module>platform-rest-core</module>
    <module>platform-service-runtime-rest</module>
  </modules>

  <properties>
    <java.version>21</java.version>
    <!-- https://docs.spring.io/spring-boot/maven-plugin/packaging.html
    <spring-boot.repackage.skip>true</spring-boot.repackage.skip>
    -->
    <spring-boot.version>3.3.6</spring-boot.version>

    <maven.compiler.release>${java.version}</maven.compiler.release>

    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>

    <commons-lang3.version>3.16.0</commons-lang3.version>
  </properties>

</project>
