<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>ex-up-down-stream-upstream</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>ex-up-down-stream-upstream</name>
  <description>Platform examples ex-up-down-stream-upstream</description>

  <parent>
    <groupId>com.github.emw7.platform.extra.examples.up-down-stream</groupId>
    <artifactId>up-down-stream</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <dependencies>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing-bridge-otel</artifactId>
    </dependency>

    <!--region EMW7 -->
    <dependency>
      <groupId>com.github.emw7</groupId>
      <artifactId>platform-service-runtime</artifactId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>
    <!--endregion EMW7 -->

    <!--region TEST -->
    <!--endregion TEST -->

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>
