package com.github.emw7.platform.log.tracing;

import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import io.micrometer.tracing.Tracer;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

class LogTracingUtilTest {

  @Test
  void generateTraceId() {
    final String actual= LogTracingUtil.generateTraceId();
    Assertions.assertThat(actual)
        .as("trace-id is not null").isNotNull()
        // 32 chars-long hex string.
        .as("trace is a 32 chars long hex string").matches("^[0-9A-Fa-f]{32}$");
  }

  @Test
  void generateSpanId() {
    final String actual= LogTracingUtil.generateSpanId();
    Assertions.assertThat(actual)
        .as("span-id is not null").isNotNull()
        // 16 chars-long hex string.
        .as("span is a 16 chars long hex string").matches("^[0-9A-Fa-f]{16}$");
  }

  @Test
  void traceIdNoCurrentSpan() {
    final Tracer tracer= Mockito.mock(Tracer.class);
    doReturn(null).when(tracer).currentSpan();
    final String actual= LogTracingUtil.traceId(tracer);
    Assertions.assertThat(actual)
        .as("trace-id is empty string if there is not current span").isEmpty();
    verify(tracer, times(1)).currentSpan();
  }

  @Test
  void traceIdCurrentSpanAutogenerated() {
    final Tracer tracer= Mockito.mock(Tracer.class);
    doReturn(new LogTracingSpan()).when(tracer).currentSpan();
    final String actual= LogTracingUtil.spanId(tracer);
    // 16 chars-long hex string.
    Assertions.assertThat(actual).as("span-id has generated (unpredictable) value").matches("^[0-9A-Fa-f]{16}$");
    verify(tracer, times(1)).currentSpan();
  }

  @Test
  void traceIdCurrentSpanProvided() {
    final Tracer tracer= Mockito.mock(Tracer.class);
    final String traceId= LogTracingUtil.generateTraceId();
    doReturn(new LogTracingSpan(traceId)).when(tracer).currentSpan();
    final String actual= LogTracingUtil.traceId(tracer);
    Assertions.assertThat(actual).as("trace-id has provided value").isEqualTo(traceId);
    verify(tracer, times(1)).currentSpan();
  }

  @Test
  void spanIdNoCurrentSpan() {
    final Tracer tracer= Mockito.mock(Tracer.class);
    doReturn(null).when(tracer).currentSpan();
    final String actual= LogTracingUtil.spanId(tracer);
    Assertions.assertThat(actual)
        .as("span-id is empty string is there is not current span").isEmpty();
    verify(tracer, times(1)).currentSpan();
  }

  @Test
  void spanIdCurrentSpanAutogenerated() {
    final Tracer tracer= Mockito.mock(Tracer.class);
    doReturn(new LogTracingSpan()).when(tracer).currentSpan();
    final String actual= LogTracingUtil.spanId(tracer);
    // 16 chars-long hex string.
    Assertions.assertThat(actual).as("span-id has generated (unpredictable) value").matches("^[0-9A-Fa-f]{16}$");
    verify(tracer, times(1)).currentSpan();
  }

  @Test
  void spanIdCurrentSpanProvided() {
    final Tracer tracer= Mockito.mock(Tracer.class);
    final String traceId= LogTracingUtil.generateTraceId();
    final String spanId= LogTracingUtil.generateSpanId();
    doReturn(new LogTracingSpan(traceId,spanId)).when(tracer).currentSpan();
    final String actual= LogTracingUtil.spanId(tracer);
    Assertions.assertThat(actual).as("span-id has provided value").isEqualTo(spanId);
    verify(tracer, times(1)).currentSpan();
  }
 
}