#region CUSTOM
com.github.emw7.platform.protocol.rest.enabled.rest-template=true
#endregion CUSTOM
spring.application.name=upstream

api.version=v1

server.servlet.context-path=/${spring.application.name}/${api.version}

server.port=8778

# do NOT change!
# ...app-page=3&app-size=15
#spring.data.web.pageable.prefix=app-
# ...app-sort=i,asc&app-sort=t,desc
#spring.data.web.sort.sort-parameter=app-sort

# do NOT change!
app.name=${spring.application.name}
