PORT=8801

LOGGING_LEVEL_COM_GITHUB_EMW7=debug

# DO NOT TOUCH FROM HERE AFTER

# retrieved from pom.xml
VERSION=x
NAME=upstream

# spring
SERVER_PORT=${PORT}
SPRING_APPLICATION_NAME=${NAME}

# dockerization and sidecar
SERVICE=${NAME}
COMPOSE_PROJECT_NAME=${NAME}
SIDECAR_PORT=${PORT}
